# Generated by Django 4.0.3 on 2022-04-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mini_title',
            field=models.CharField(default='', max_length=155),
            preserve_default=False,
        ),
    ]



