# Generated by Django 4.0.3 on 2022-05-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название смартфона')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('platform', models.CharField(max_length=100, verbose_name='Платформа')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('diagonal', models.FloatField(verbose_name='Диагональ')),
                ('ram', models.IntegerField(verbose_name='Оперативная память')),
                ('rom', models.IntegerField(verbose_name='Постоянная память')),
                ('battery', models.IntegerField(verbose_name='Емкость батареи')),
                ('nfc', models.BooleanField(default=True, verbose_name='NFC')),
                ('sim', models.IntegerField(verbose_name='Количество SIM')),
                ('five_g', models.BooleanField(default=False, verbose_name='5G интернет')),
                ('gps', models.BooleanField(default=True, verbose_name='GPS')),
                ('jack', models.BooleanField(default=True, verbose_name='Разъем 3.5мм')),
                ('processor_frequency', models.IntegerField(verbose_name='Частота процессора')),
                ('warranty', models.IntegerField(verbose_name='Гарантия')),
                ('Testing', models.IntegerField()),
            ],
        ),
    ]
