# Generated by Django 4.0.3 on 2022-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_remove_phones_testing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phones',
            options={'ordering': ['title'], 'verbose_name': 'смартфон', 'verbose_name_plural': 'Смартфоны'},
        ),
        migrations.AlterField(
            model_name='phones',
            name='platform',
            field=models.CharField(choices=[(1, 'Android'), (2, 'IOS')], max_length=100, verbose_name='Платформа'),
        ),
    ]
