# Generated by Django 4.0.3 on 2022-05-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0003_alter_phones_options_alter_phones_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='platform',
            field=models.CharField(choices=[('Android', 'Android'), ('IOS', 'IOS')], max_length=100, verbose_name='Платформа'),
        ),
    ]
