# Generated by Django 4.0.3 on 2022-05-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0004_alter_phones_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='sim',
            field=models.IntegerField(choices=[(1, '1 SIM'), (2, '2 SIM')], verbose_name='Количество SIM'),
        ),
    ]
