# Generated by Django 4.0.3 on 2022-05-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0007_tagis_alter_phones_options_alter_phones_warranty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagis',
            options={'ordering': ['id'], 'verbose_name': 'тег смартфона', 'verbose_name_plural': 'Теги смартфонов'},
        ),
        migrations.AlterModelOptions(
            name='tagsphones',
            options={'ordering': ['id'], 'verbose_name': 'связь тега и смартфона', 'verbose_name_plural': 'Связь тегов и смартфонов'},
        ),
        migrations.AlterField(
            model_name='tagsphones',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart.phones', unique=True),
        ),
        migrations.AlterField(
            model_name='tagsphones',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart.tagis', unique=True),
        ),
    ]
